# Generated by Django 4.1.7 on 2023-03-17 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoginDetails',
            fields=[
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=20)),
                ('name', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LANM', models.IntegerField()),
                ('EC', models.IntegerField()),
                ('BEEE', models.IntegerField()),
                ('PPS', models.IntegerField()),
                ('PPS_LAB', models.IntegerField(default=0)),
                ('EC_LAB', models.IntegerField()),
                ('BEEE_LAB', models.IntegerField()),
                ('IT_WORKSHOP', models.IntegerField()),
                ('TotalCredits1', models.IntegerField(default=0)),
                ('ENG', models.IntegerField(default=0)),
                ('PandS', models.IntegerField(default=0)),
                ('SCP', models.IntegerField(default=0)),
                ('PYTHON', models.IntegerField(default=0)),
                ('EG', models.IntegerField(default=0)),
                ('ENG_LAB', models.IntegerField(default=0)),
                ('SCP_LAB', models.IntegerField(default=0)),
                ('PYTHON_LAB', models.IntegerField(default=0)),
                ('TotalCredits2', models.IntegerField(default=0)),
                ('DM', models.IntegerField(default=0)),
                ('COA', models.IntegerField(default=0)),
                ('DS', models.IntegerField(default=0)),
                ('JAVA', models.IntegerField(default=0)),
                ('OS', models.IntegerField(default=0)),
                ('DS_LAB', models.IntegerField(default=0)),
                ('JAVA_LAB', models.IntegerField(default=0)),
                ('OS_LAB', models.IntegerField(default=0)),
                ('GS', models.IntegerField(default=0)),
                ('TotalCredits3', models.IntegerField(default=0)),
                ('ASOT', models.IntegerField(default=0)),
                ('DBMS', models.IntegerField(default=0)),
                ('WT', models.IntegerField(default=0)),
                ('DAA', models.IntegerField(default=0)),
                ('CC', models.IntegerField(default=0)),
                ('DBMS_LAB', models.IntegerField(default=0)),
                ('WT_LAB', models.IntegerField(default=0)),
                ('DAA_LAB', models.IntegerField(default=0)),
                ('ES', models.IntegerField(default=0)),
                ('TotalCredits4', models.IntegerField(default=0)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.logindetails')),
            ],
        ),
        migrations.CreateModel(
            name='Queries',
            fields=[
                ('name', models.CharField(default=0, max_length=100, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.logindetails')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DM', models.IntegerField(default=0)),
                ('CNS', models.IntegerField(default=0)),
                ('EEA', models.IntegerField(default=0)),
                ('GB', models.IntegerField(default=0)),
                ('CD', models.IntegerField(default=0)),
                ('QA', models.IntegerField(default=0)),
                ('DM_LAB', models.IntegerField(default=0)),
                ('CD_LAB', models.IntegerField(default=0)),
                ('ENG_LAB', models.IntegerField(default=0)),
                ('DM_TOTAL', models.IntegerField(default=0)),
                ('CNS_TOTAL', models.IntegerField(default=0)),
                ('EEA_TOTAL', models.IntegerField(default=0)),
                ('GB_TOTAL', models.IntegerField(default=0)),
                ('CD_TOTAL', models.IntegerField(default=0)),
                ('QA_TOTAL', models.IntegerField(default=0)),
                ('DM_LAB_TOTAL', models.IntegerField(default=0)),
                ('CD_LAB_TOTAL', models.IntegerField(default=0)),
                ('ENG_LAB_TOTAL', models.IntegerField(default=0)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.logindetails')),
            ],
        ),
    ]
