# Generated by Django 4.1.7 on 2023-03-17 16:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('Year', models.IntegerField()),
                ('Dept', models.CharField(max_length=20)),
                ('Monday', models.CharField(max_length=20)),
                ('Tuesday', models.CharField(max_length=20)),
                ('Wednesday', models.CharField(max_length=20)),
                ('Thursday', models.CharField(max_length=20)),
                ('Friday', models.CharField(max_length=20)),
                ('Saturday', models.CharField(max_length=20)),
            ],
        ),
    ]
