# Generated by Django 4.1.7 on 2023-03-17 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_timetable'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timetable',
            old_name='Friday',
            new_name='C1',
        ),
        migrations.RenameField(
            model_name='timetable',
            old_name='Monday',
            new_name='C2',
        ),
        migrations.RenameField(
            model_name='timetable',
            old_name='Saturday',
            new_name='C3',
        ),
        migrations.RenameField(
            model_name='timetable',
            old_name='Thursday',
            new_name='C4',
        ),
        migrations.RenameField(
            model_name='timetable',
            old_name='Tuesday',
            new_name='C5',
        ),
        migrations.RenameField(
            model_name='timetable',
            old_name='Wednesday',
            new_name='C6',
        ),
        migrations.AddField(
            model_name='timetable',
            name='Day',
            field=models.CharField(default='sunday', max_length=20),
        ),
    ]
