# Generated by Django 4.1.7 on 2023-03-17 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_rename_friday_timetable_c1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='C7',
            field=models.CharField(default='sports', max_length=20),
        ),
    ]
