# Generated by Django 4.1.7 on 2023-03-18 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_timetable_c7'),
    ]

    operations = [
        migrations.AddField(
            model_name='logindetails',
            name='usertype',
            field=models.CharField(default='usertype', max_length=30),
        ),
    ]
