# Generated by Django 4.1.7 on 2023-03-18 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_logindetails_dept'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub', models.CharField(default='sub', max_length=30)),
                ('text', models.CharField(default='text', max_length=200)),
            ],
        ),
    ]
