# Generated by Django 4.1.7 on 2023-03-18 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_assignments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignments',
            name='id',
        ),
        migrations.AlterField(
            model_name='assignments',
            name='sub',
            field=models.CharField(default='sub', max_length=30, primary_key=True, serialize=False),
        ),
    ]
