# Generated by Django 4.1.7 on 2023-03-18 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_remove_assignments_id_alter_assignments_sub'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignments',
            old_name='text',
            new_name='mid',
        ),
        migrations.AddField(
            model_name='assignments',
            name='q1',
            field=models.CharField(default='text', max_length=200),
        ),
        migrations.AddField(
            model_name='assignments',
            name='q2',
            field=models.CharField(default='text', max_length=200),
        ),
        migrations.AddField(
            model_name='assignments',
            name='q3',
            field=models.CharField(default='text', max_length=200),
        ),
        migrations.AddField(
            model_name='assignments',
            name='q4',
            field=models.CharField(default='text', max_length=200),
        ),
        migrations.AddField(
            model_name='assignments',
            name='q5',
            field=models.CharField(default='text', max_length=200),
        ),
    ]
