# Generated by Django 4.1.7 on 2023-03-31 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_rename_text_assignments_mid_assignments_q1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignments',
            name='mid',
            field=models.CharField(blank=True, default='mid', max_length=200),
        ),
        migrations.AlterField(
            model_name='assignments',
            name='q1',
            field=models.CharField(blank=True, default='text', max_length=200),
        ),
        migrations.AlterField(
            model_name='assignments',
            name='q2',
            field=models.CharField(blank=True, default='text', max_length=200),
        ),
        migrations.AlterField(
            model_name='assignments',
            name='q3',
            field=models.CharField(blank=True, default='text', max_length=200),
        ),
        migrations.AlterField(
            model_name='assignments',
            name='q4',
            field=models.CharField(blank=True, default='text', max_length=200),
        ),
        migrations.AlterField(
            model_name='assignments',
            name='q5',
            field=models.CharField(blank=True, default='text', max_length=200),
        ),
    ]
