# Generated by Django 4.1.7 on 2023-04-01 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_alter_assignments_mid_alter_assignments_q1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignments',
            name='q10',
            field=models.CharField(default='text', max_length=200),
        ),
        migrations.AddField(
            model_name='assignments',
            name='q6',
            field=models.CharField(default='text', max_length=200),
        ),
        migrations.AddField(
            model_name='assignments',
            name='q7',
            field=models.CharField(default='text', max_length=200),
        ),
        migrations.AddField(
            model_name='assignments',
            name='q8',
            field=models.CharField(default='text', max_length=200),
        ),
        migrations.AddField(
            model_name='assignments',
            name='q9',
            field=models.CharField(default='text', max_length=200),
        ),
    ]
