# Generated by Django 4.1.7 on 2023-04-01 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_assignments_q10_assignments_q6_assignments_q7_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignments',
            name='q1',
            field=models.CharField(blank=True, default='text', max_length=200),
        ),
        migrations.AlterField(
            model_name='assignments',
            name='q10',
            field=models.CharField(blank=True, default='text', max_length=200),
        ),
        migrations.AlterField(
            model_name='assignments',
            name='q2',
            field=models.CharField(blank=True, default='text', max_length=200),
        ),
        migrations.AlterField(
            model_name='assignments',
            name='q3',
            field=models.CharField(blank=True, default='text', max_length=200),
        ),
        migrations.AlterField(
            model_name='assignments',
            name='q4',
            field=models.CharField(blank=True, default='text', max_length=200),
        ),
        migrations.AlterField(
            model_name='assignments',
            name='q5',
            field=models.CharField(blank=True, default='text', max_length=200),
        ),
        migrations.AlterField(
            model_name='assignments',
            name='q6',
            field=models.CharField(blank=True, default='text', max_length=200),
        ),
        migrations.AlterField(
            model_name='assignments',
            name='q7',
            field=models.CharField(blank=True, default='text', max_length=200),
        ),
        migrations.AlterField(
            model_name='assignments',
            name='q8',
            field=models.CharField(blank=True, default='text', max_length=200),
        ),
        migrations.AlterField(
            model_name='assignments',
            name='q9',
            field=models.CharField(blank=True, default='text', max_length=200),
        ),
    ]
