# Generated by Django 4.1.7 on 2023-04-01 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_alter_assignments_q1_alter_assignments_q10_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignments',
            name='q10',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
