# Generated by Django 4.1.7 on 2023-04-01 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_alter_assignments_q1_alter_assignments_q10_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mid1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Java_Programming_Cse', models.IntegerField()),
                ('Data_Structures_Cse', models.IntegerField()),
                ('Web_Technologies_Cse', models.IntegerField()),
            ],
        ),
    ]
