# Generated by Django 4.1.7 on 2023-04-01 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_mid1'),
    ]

    operations = [
        migrations.AddField(
            model_name='mid1',
            name='username',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='user.logindetails'),
        ),
    ]
