# Generated by Django 4.1.7 on 2023-04-01 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_mid1_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mid2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Java_Programming_Cse', models.IntegerField()),
                ('Data_Structures_Cse', models.IntegerField()),
                ('Web_Technologies_Cse', models.IntegerField()),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.logindetails')),
            ],
        ),
    ]
