# Generated by Django 4.1.7 on 2023-04-01 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_remove_mid1_id_alter_mid1_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mid2',
            name='id',
        ),
        migrations.AlterField(
            model_name='mid2',
            name='username',
            field=models.CharField(default='', max_length=30, primary_key=True, serialize=False),
        ),
    ]
