# Generated by Django 4.1.7 on 2023-04-01 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_remove_mid2_id_alter_mid2_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mid1',
            name='Data_Structures_Cse',
            field=models.IntegerField(default=True),
        ),
        migrations.AlterField(
            model_name='mid1',
            name='Java_Programming_Cse',
            field=models.CharField(default=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='mid1',
            name='Web_Technologies_Cse',
            field=models.IntegerField(default=True),
        ),
    ]
