# Generated by Django 4.1.7 on 2023-05-17 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0025_semester_c1_semester_c10_semester_c11_semester_c12_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester',
            name='c1',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='semester',
            name='c10',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='semester',
            name='c11',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='semester',
            name='c12',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='semester',
            name='c13',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='semester',
            name='c14',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='semester',
            name='c15',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='semester',
            name='c16',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='semester',
            name='c17',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='semester',
            name='c18',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='semester',
            name='c19',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='semester',
            name='c2',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='semester',
            name='c20',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='semester',
            name='c21',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='semester',
            name='c22',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='semester',
            name='c23',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='semester',
            name='c24',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='semester',
            name='c25',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='semester',
            name='c26',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='semester',
            name='c27',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='semester',
            name='c28',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='semester',
            name='c29',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='semester',
            name='c3',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='semester',
            name='c30',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='semester',
            name='c31',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='semester',
            name='c32',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='semester',
            name='c33',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='semester',
            name='c34',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='semester',
            name='c4',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='semester',
            name='c5',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='semester',
            name='c6',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='semester',
            name='c7',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='semester',
            name='c8',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='semester',
            name='c9',
            field=models.CharField(default=0, max_length=10),
        ),
    ]
