# Generated by Django 4.1.7 on 2023-05-22 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0028_totalattendance_alter_timetable_c7'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='CD_LAB_TOTAL',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='CD_TOTAL',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='CNS_TOTAL',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='DM_LAB_TOTAL',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='DM_TOTAL',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='EEA_TOTAL',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='ENG_LAB_TOTAL',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='GB_TOTAL',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='QA_TOTAL',
        ),
    ]
