# Generated by Django 4.1.7 on 2023-05-24 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0029_remove_attendance_cd_lab_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mid1',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='mid2',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
