# Generated by Django 4.1.7 on 2023-06-14 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0030_mid1_name_mid2_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mid1',
            name='name',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='mid2',
            name='name',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
