# Generated by Django 4.1.7 on 2023-06-14 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0032_alter_mid2_name_alter_mid2_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mid1',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='mid2',
            name='name',
            field=models.CharField(blank=True, default='', max_length=50, primary_key=True, serialize=False),
        ),
    ]
