# Generated by Django 4.1.7 on 2023-06-14 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0034_alter_mid2_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mid2',
        ),
    ]
