# Generated by Django 4.1.7 on 2023-06-14 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0035_delete_mid2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mid2',
            fields=[
                ('username', models.CharField(default='', max_length=30)),
                ('name', models.CharField(default='', max_length=50, primary_key=True, serialize=False)),
                ('Java_Programming_Cse', models.CharField(blank=True, max_length=10)),
                ('Data_Structures_Cse', models.CharField(blank=True, max_length=10)),
                ('Web_Technologies_Cse', models.CharField(blank=True, max_length=10)),
            ],
        ),
    ]
