# Generated by Django 4.1.7 on 2023-08-18 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0037_message_alter_assignments_q1_alter_assignments_q10_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mid2',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='mid2',
            name='username',
            field=models.CharField(default='', max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='semester',
            name='c1',
            field=models.CharField(default=4, max_length=10),
        ),
        migrations.AlterField(
            model_name='semester',
            name='c10',
            field=models.CharField(default=3, max_length=10),
        ),
        migrations.AlterField(
            model_name='semester',
            name='c11',
            field=models.CharField(default=4, max_length=10),
        ),
        migrations.AlterField(
            model_name='semester',
            name='c12',
            field=models.CharField(default=4, max_length=10),
        ),
        migrations.AlterField(
            model_name='semester',
            name='c13',
            field=models.CharField(default=3, max_length=10),
        ),
        migrations.AlterField(
            model_name='semester',
            name='c14',
            field=models.CharField(default=1, max_length=10),
        ),
        migrations.AlterField(
            model_name='semester',
            name='c15',
            field=models.CharField(default=1, max_length=10),
        ),
        migrations.AlterField(
            model_name='semester',
            name='c16',
            field=models.CharField(default=2, max_length=10),
        ),
        migrations.AlterField(
            model_name='semester',
            name='c17',
            field=models.CharField(default=3, max_length=10),
        ),
        migrations.AlterField(
            model_name='semester',
            name='c18',
            field=models.CharField(default=3, max_length=10),
        ),
        migrations.AlterField(
            model_name='semester',
            name='c19',
            field=models.CharField(default=3, max_length=10),
        ),
        migrations.AlterField(
            model_name='semester',
            name='c2',
            field=models.CharField(default=4, max_length=10),
        ),
        migrations.AlterField(
            model_name='semester',
            name='c20',
            field=models.CharField(default=3, max_length=10),
        ),
        migrations.AlterField(
            model_name='semester',
            name='c21',
            field=models.CharField(default=3, max_length=10),
        ),
        migrations.AlterField(
            model_name='semester',
            name='c22',
            field=models.CharField(default=1.5, max_length=10),
        ),
        migrations.AlterField(
            model_name='semester',
            name='c23',
            field=models.CharField(default=1.5, max_length=10),
        ),
        migrations.AlterField(
            model_name='semester',
            name='c24',
            field=models.CharField(default=2, max_length=10),
        ),
        migrations.AlterField(
            model_name='semester',
            name='c26',
            field=models.CharField(default=3, max_length=10),
        ),
        migrations.AlterField(
            model_name='semester',
            name='c27',
            field=models.CharField(default=3, max_length=10),
        ),
        migrations.AlterField(
            model_name='semester',
            name='c28',
            field=models.CharField(default=3, max_length=10),
        ),
        migrations.AlterField(
            model_name='semester',
            name='c29',
            field=models.CharField(default=3, max_length=10),
        ),
        migrations.AlterField(
            model_name='semester',
            name='c3',
            field=models.CharField(default=3, max_length=10),
        ),
        migrations.AlterField(
            model_name='semester',
            name='c30',
            field=models.CharField(default=3, max_length=10),
        ),
        migrations.AlterField(
            model_name='semester',
            name='c31',
            field=models.CharField(default=2, max_length=10),
        ),
        migrations.AlterField(
            model_name='semester',
            name='c32',
            field=models.CharField(default=1.5, max_length=10),
        ),
        migrations.AlterField(
            model_name='semester',
            name='c33',
            field=models.CharField(default=1.5, max_length=10),
        ),
        migrations.AlterField(
            model_name='semester',
            name='c4',
            field=models.CharField(default=3, max_length=10),
        ),
        migrations.AlterField(
            model_name='semester',
            name='c5',
            field=models.CharField(default=3, max_length=10),
        ),
        migrations.AlterField(
            model_name='semester',
            name='c6',
            field=models.CharField(default=1, max_length=10),
        ),
        migrations.AlterField(
            model_name='semester',
            name='c7',
            field=models.CharField(default=1.5, max_length=10),
        ),
        migrations.AlterField(
            model_name='semester',
            name='c8',
            field=models.CharField(default=1.5, max_length=10),
        ),
        migrations.AlterField(
            model_name='semester',
            name='c9',
            field=models.CharField(default=3, max_length=10),
        ),
    ]
